name: CI/CD to Azure App Service

on:
  push:
    branches: [ main ]   # deploy on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      # 3. Install deps & build React app
      - name: Install & Build
        run: |
          npm ci
          npm run build
          # package dist/ into a zip
          cd dist && zip -r ../app.zip . && cd ..

      # 4. Login to Azure with SP credentials
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 5. Deploy zip to App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.WEBAPP_NAME }}
          package: app.zip
